name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Install Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Setup Apache Spark
      # You may pin to the exact commit or the version.
      # uses: vemonet/setup-spark@3a793c8989d2bd289406efd98f21d00096e6403a
      uses: vemonet/setup-spark@v1
      with:
        spark-version: 3.1.3
        
    - name: Set up KSQL
      uses: addnab/docker-run-action@v3
      with:
        image: confluentinc/cp-ksql-server:5.4.2
        options: -v ${{ github.workspace }}:/home/mksql -e KSQL_BOOTSTRAP_SERVERS=localhost:9092 -e KSQL_LISTENERS=http://0.0.0.0:8088/
        
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt


    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
